# Configuraci贸n para Netlify
# Configuraci贸n sugerida por IA para subir la app a Netlify (frontend)

# Configuraci贸n de build, para construir el proyecto

[build]
  command = "npm run build"
  publish = "build"

# Configuraci贸n de las redirecciones

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200